// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read the live process env (not just a dotenv .env FILE): in containers/CI the
    // URL is injected via env_file / -e, which prisma's env() helper does not see.
    // dotenv/config still hydrates process.env from a .env file for local dev.
    url: process.env.DATABASE_URL,
  },
});