import { ClientReportSnapshot } from './types';

function escapeCsv(val: any): string {
  if (val === null || val === undefined) return '""';
  const str = String(val).replace(/"/g, '""');
  return `"${str}"`;
}

/** Escape a value before interpolating it into the exported HTML template. */
function escapeHtml(val: unknown): string {
  if (val === null || val === undefined) return '';
  return String(val)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function exportReportToCSV(snapshot: ClientReportSnapshot): string {
  const lines: string[] = [];

  // Section 1: Metadata
  lines.push('=== CLIENT REPORT METADATA ===');
  lines.push(`Client,${escapeCsv(snapshot.meta.clientName)}`);
  lines.push(`Campaign,${escapeCsv(snapshot.meta.campaignName || 'All Campaigns')}`);
  lines.push(`Period Start,${escapeCsv(snapshot.meta.periodStart)}`);
  lines.push(`Period End,${escapeCsv(snapshot.meta.periodEnd)}`);
  lines.push(`Generated By,${escapeCsv(snapshot.meta.generatedByName)}`);
  lines.push(`Approved By,${escapeCsv(snapshot.meta.approvedByName || 'Draft')}`);
  lines.push('');

  // Section 2: Executive Insights
  lines.push('=== EXECUTIVE INSIGHTS ===');
  lines.push(`Executive Summary,${escapeCsv(snapshot.insights.summary || '')}`);
  lines.push(`Key Wins,${escapeCsv(snapshot.insights.keyWins.join(' | '))}`);
  lines.push(`Blockers,${escapeCsv(snapshot.insights.blockers.join(' | '))}`);
  lines.push(`Recommendations,${escapeCsv(snapshot.insights.recommendations.join(' | '))}`);
  lines.push(`Client Actions,${escapeCsv(snapshot.insights.clientActions.join(' | '))}`);
  lines.push('');

  // Section 3: KPI Scorecard
  lines.push('=== CAMPAIGN KPI SCORECARD ===');
  lines.push('KPI,Value');
  lines.push(`Total Leads Assigned,${snapshot.kpis.totalLeadsAssigned}`);
  lines.push(`New Leads Added,${snapshot.kpis.newLeadsAdded}`);
  lines.push(`Prospects Contacted,${snapshot.kpis.leadsTouched}`);
  lines.push(`Touchpoints Completed,${snapshot.kpis.touchpointsCompleted}`);
  lines.push(`Replies Received,${snapshot.kpis.replies}`);
  lines.push(`Reply Rate,${(snapshot.kpis.replyRate * 100).toFixed(1)}%`);
  lines.push(`Meetings Booked,${snapshot.kpis.meetingsBooked}`);
  lines.push(`Meetings Completed,${snapshot.kpis.meetingsCompleted}`);
  lines.push(`No Shows,${snapshot.kpis.noShows}`);
  lines.push(`Qualified Meetings,${snapshot.kpis.qualifiedMeetings}`);
  lines.push(`Opportunities Submitted,${snapshot.kpis.opportunitiesSubmitted}`);
  lines.push(`Client Accepted Opportunities,${snapshot.kpis.clientAcceptedOpportunities}`);
  lines.push(`Client Acceptance Rate,${(snapshot.kpis.clientAcceptanceRate * 100).toFixed(1)}%`);
  lines.push(`Active Pipeline Value,$${snapshot.kpis.activePipelineValue.toLocaleString()}`);
  lines.push(`Won Value,$${snapshot.kpis.wonValue.toLocaleString()}`);
  lines.push('');

  // Section 4: Channel Activity Breakdown
  lines.push('=== OUTREACH BY CHANNEL ===');
  lines.push('Channel,Touchpoints,Replies,Meetings Booked,Conversion Rate');
  for (const ch of snapshot.channels) {
    lines.push(
      `${escapeCsv(ch.label)},${ch.touchpoints},${ch.replies},${ch.meetingsBooked ?? 'n/a'},${(ch.conversionRate * 100).toFixed(1)}%`
    );
  }
  lines.push('');

  // Section 4b: Email Channel Health
  if (snapshot.emailChannelHealth) {
    lines.push('=== EMAIL CHANNEL DELIVERABILITY & HEALTH ===');
    lines.push(`Overall Health,${snapshot.emailChannelHealth.overall}`);
    lines.push(`Emails Sent,${snapshot.emailChannelHealth.emailsSent}`);
    lines.push(`Bounce Rate,${(snapshot.emailChannelHealth.bounceRate * 100).toFixed(2)}%`);
    lines.push(`Reply Rate,${(snapshot.emailChannelHealth.replyRate * 100).toFixed(2)}%`);
    lines.push(`Corrective Actions,${escapeCsv(snapshot.emailChannelHealth.correctiveActions.join(' | '))}`);
    lines.push('');
  }

  // Section 5: Meetings Log
  lines.push('=== MEETINGS LOG ===');
  lines.push('Company,Contact,Scheduled Date,Status,Outcome,SDR,Notes');
  for (const m of snapshot.meetings) {
    lines.push(
      `${escapeCsv(m.company)},${escapeCsv(m.contactName || m.contactTitle || '')},${escapeCsv(m.scheduledAt || 'Not yet scheduled')},${escapeCsv(m.status)},${escapeCsv(m.outcome || '')},${escapeCsv(m.sdrDisplayName || '')},${escapeCsv(m.summaryNotes || '')}`
    );
  }
  lines.push('');

  // Section 6: Opportunity Handoffs
  lines.push('=== OPPORTUNITY PIPELINE ===');
  lines.push('Company,Opportunity Title,Stage,Handoff Status,Value,Probability,Next Step');
  for (const opp of snapshot.opportunities) {
    lines.push(
      `${escapeCsv(opp.company)},${escapeCsv(opp.title)},${escapeCsv(opp.stage)},${escapeCsv(opp.handoffStatus)},${opp.value ? `$${opp.value}` : ''},${opp.probability ? `${opp.probability}%` : ''},${escapeCsv(opp.nextStep || '')}`
    );
  }
  lines.push('');

  // Section 7: SDR Performance
  lines.push('=== SDR PERFORMANCE ===');
  lines.push('Rep,Prospects Touched,Touchpoints,Replies,Meetings Booked,Accepted Ops');
  for (const rep of snapshot.reps) {
    lines.push(
      `${escapeCsv(rep.displayName)},${rep.leadsTouched},${rep.touchpoints},${rep.replies},${rep.meetingsBooked},${rep.acceptedOpportunities}`
    );
  }

  return lines.join('\n');
}

/**
 * The report's real approval state, passed in from the row rather than assumed.
 *
 * The header used to be the string literal "Status: Approved", so an unapproved
 * draft exported to the client claiming a sign-off that had not happened. The
 * approve/freeze gate exists precisely so a manager signs off before a client
 * sees numbers; printing "Approved" on a draft does not just bypass that gate,
 * it misrepresents it.
 */
export interface ReportApprovalState {
  status: string;
  approvedByName?: string | null;
  approvedAt?: Date | string | null;
}

export function exportReportToHTML(
  snapshot: ClientReportSnapshot,
  approval?: ReportApprovalState
): string {
  const periodStartFmt = new Date(snapshot.meta.periodStart).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const periodEndFmt = new Date(snapshot.meta.periodEnd).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  const status = approval?.status ?? 'draft';
  const isApproved = status === 'approved' || status === 'shared';
  const approver = approval?.approvedByName || snapshot.meta.approvedByName;
  const statusLine = isApproved
    ? `Status: Approved${approver ? ` by ${escapeHtml(approver)}` : ''} &bull; Version ${escapeHtml(snapshot.meta.version || 'v1')}`
    : `Status: ${escapeHtml(status.toUpperCase())} &mdash; not approved for client distribution`;
  const draftBanner = isApproved
    ? ''
    : `<div style="background:#fef3c7;border:1px solid #f59e0b;color:#92400e;padding:8px 12px;border-radius:6px;margin-bottom:12px;font-size:12px;font-weight:600;">
        DRAFT &mdash; these figures are unapproved and must not be sent to the client.
      </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${snapshot.meta.clientName} - Campaign Performance Report</title>
  <style>
    @page { size: A4 portrait; margin: 15mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #1e293b;
      background: #ffffff;
      margin: 0;
      padding: 24px;
      font-size: 13px;
      line-height: 1.5;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 16px;
      margin-bottom: 20px;
    }
    .brand {
      font-size: 20px;
      font-weight: 700;
      color: #d42b1e;
      letter-spacing: -0.5px;
    }
    .title {
      font-size: 16px;
      font-weight: 600;
      color: #0f172a;
      margin-top: 4px;
    }
    .meta-badge {
      display: inline-block;
      padding: 4px 10px;
      background: #f1f5f9;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 500;
      color: #475569;
    }
    .grid-kpis {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-bottom: 24px;
    }
    .kpi-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 12px;
    }
    .kpi-label {
      font-size: 11px;
      text-transform: uppercase;
      font-weight: 600;
      color: #64748b;
    }
    .kpi-value {
      font-size: 20px;
      font-weight: 700;
      color: #0f172a;
      margin-top: 4px;
    }
    .kpi-sub {
      font-size: 11px;
      color: #16a34a;
      margin-top: 2px;
      font-weight: 500;
    }
    .section-title {
      font-size: 14px;
      font-weight: 700;
      color: #0f172a;
      margin-top: 24px;
      margin-bottom: 10px;
      border-left: 3px solid #d42b1e;
      padding-left: 8px;
    }
    .card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 14px;
      margin-bottom: 16px;
    }
    .insights-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 12px;
      margin-bottom: 16px;
    }
    ul {
      margin: 0;
      padding-left: 18px;
    }
    li {
      margin-bottom: 4px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
      margin-bottom: 16px;
      font-size: 12px;
    }
    th {
      background: #f1f5f9;
      text-align: left;
      padding: 8px 10px;
      border-bottom: 1px solid #cbd5e1;
      color: #475569;
      font-weight: 600;
    }
    td {
      padding: 8px 10px;
      border-bottom: 1px solid #e2e8f0;
      color: #334155;
    }
    .badge {
      display: inline-block;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 600;
    }
    .badge-success { background: #dcfce7; color: #15803d; }
    .badge-info { background: #e0f2fe; color: #0369a1; }
    .badge-warning { background: #fef3c7; color: #b45309; }
    .footer {
      margin-top: 30px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 11px;
      color: #94a3b8;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none; }
      .page-break { page-break-before: always; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom: 16px; text-align: right;">
    <button onclick="window.print()" style="background: #d42b1e; color: #fff; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: 600;">
      Print / Save as PDF
    </button>
  </div>

  ${draftBanner}

  <div class="header">
    <div>
      <div class="brand">SALESFLOW &bull; CAMPAIGN REPORT</div>
      <div class="title">${snapshot.meta.clientName} &mdash; ${snapshot.meta.campaignName || 'Omnichannel Outreach'}</div>
    </div>
    <div style="text-align: right;">
      <div class="meta-badge">${periodStartFmt} &ndash; ${periodEndFmt}</div>
      <div style="font-size: 11px; color: #64748b; margin-top: 4px;">${statusLine}</div>
    </div>
  </div>

  <!-- KPI Scorecard -->
  <div class="grid-kpis">
    <div class="kpi-card">
      <div class="kpi-label">Prospects Contacted</div>
      <div class="kpi-value">${snapshot.kpis.leadsTouched.toLocaleString()}</div>
      <div class="kpi-sub">${snapshot.kpis.touchpointsCompleted.toLocaleString()} total touches</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Replies Received</div>
      <div class="kpi-value">${snapshot.kpis.replies}</div>
      <div class="kpi-sub">${(snapshot.kpis.replyRate * 100).toFixed(1)}% reply rate</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Booked Meetings</div>
      <div class="kpi-value">${snapshot.kpis.meetingsBooked}</div>
      <div class="kpi-sub">${snapshot.kpis.qualifiedMeetings} qualified</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Accepted Opportunities</div>
      <div class="kpi-value">${snapshot.kpis.clientAcceptedOpportunities}</div>
      <div class="kpi-sub">$${snapshot.kpis.activePipelineValue.toLocaleString()} active pipeline</div>
    </div>
  </div>

  <!-- Executive Summary -->
  <div class="section-title">Executive Summary</div>
  <div class="card">
    <p style="margin: 0; font-size: 13px; color: #334155; line-height: 1.6;">
      ${snapshot.insights.summary || 'Outreach activities conducted over this period delivered positive engagement and scheduled discovery calls with target decision-makers.'}
    </p>
  </div>

  <!-- Wins & Next Actions -->
  <div class="insights-grid">
    <div class="card">
      <strong style="color: #15803d; display: block; margin-bottom: 8px;">Key Performance Highlights</strong>
      <ul>
        ${snapshot.insights.keyWins.map(w => `<li>${w}</li>`).join('')}
      </ul>
    </div>
    <div class="card">
      <strong style="color: #0369a1; display: block; margin-bottom: 8px;">Strategic Recommendations</strong>
      <ul>
        ${snapshot.insights.recommendations.map(r => `<li>${r}</li>`).join('')}
      </ul>
    </div>
  </div>

  <!-- Channel Breakdown -->
  <div class="section-title">Outreach by Channel</div>
  <table>
    <thead>
      <tr>
        <th>Channel</th>
        <th>Touchpoints</th>
        <th>Replies</th>
        <th>Meetings Booked</th>
        <th>Conversion Rate</th>
      </tr>
    </thead>
    <tbody>
      ${snapshot.channels.map(ch => `
        <tr>
          <td><strong>${ch.label}</strong></td>
          <td>${ch.touchpoints.toLocaleString()}</td>
          <td>${ch.replies}</td>
          <td>${ch.meetingsBooked ?? '&mdash;'}</td>
          <td>${(ch.conversionRate * 100).toFixed(1)}%</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  ${snapshot.emailChannelHealth ? `
  <!-- Email Channel Health & Deliverability -->
  <div class="section-title">Email Channel Health & Deliverability</div>
  <div class="card" style="display: flex; justify-content: space-between; align-items: center; border-left: 4px solid ${snapshot.emailChannelHealth.overall === 'Good' ? '#16a34a' : snapshot.emailChannelHealth.overall === 'Watch' ? '#d97706' : '#dc2626'};">
    <div>
      <div style="font-weight: 700; font-size: 13px; margin-bottom: 4px;">
        Overall Posture: <span class="badge ${snapshot.emailChannelHealth.overall === 'Good' ? 'badge-success' : snapshot.emailChannelHealth.overall === 'Watch' ? 'badge-warning' : 'badge-danger'}" style="${snapshot.emailChannelHealth.overall === 'Risk' ? 'background: #fee2e2; color: #b91c1c;' : ''}">${snapshot.emailChannelHealth.overall}</span>
      </div>
      <div style="font-size: 12px; color: #475569;">
        ${snapshot.emailChannelHealth.correctiveActions.join(' ')}
      </div>
    </div>
    <div style="text-align: right; min-width: 150px;">
      <div style="font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: 600;">Bounce Rate</div>
      <div style="font-size: 15px; font-weight: 700; color: #0f172a;">${(snapshot.emailChannelHealth.bounceRate * 100).toFixed(2)}%</div>
      <div style="font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: 600; margin-top: 4px;">Reply Rate</div>
      <div style="font-size: 13px; font-weight: 600; color: #0f172a;">${(snapshot.emailChannelHealth.replyRate * 100).toFixed(2)}%</div>
    </div>
  </div>
  ` : ''}

  <!-- Meetings Log -->
  <div class="section-title">Booked Meetings & Outcomes</div>
  <table>
    <thead>
      <tr>
        <th>Company</th>
        <th>Scheduled</th>
        <th>Status</th>
        <th>Outcome</th>
        <th>Next Step</th>
      </tr>
    </thead>
    <tbody>
      ${snapshot.meetings.slice(0, 10).map(m => `
        <tr>
          <td><strong>${m.company}</strong></td>
          <td>${m.scheduledAt ? new Date(m.scheduledAt).toLocaleDateString() : 'Not yet scheduled'}</td>
          <td><span class="badge ${m.status === 'completed' ? 'badge-success' : 'badge-info'}">${m.status}</span></td>
          <td>${m.outcome || 'Pending'}</td>
          <td>${m.nextStep || 'Follow-up as scheduled'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  ${snapshot.opportunities && snapshot.opportunities.length > 0 ? `
  <!-- Opportunity Pipeline -->
  <div class="section-title">Opportunity Pipeline</div>
  <table>
    <thead>
      <tr>
        <th>Company</th>
        <th>Opportunity Title</th>
        <th>Stage</th>
        <th>Handoff Status</th>
        <th>Value</th>
        <th>Next Step</th>
      </tr>
    </thead>
    <tbody>
      ${snapshot.opportunities.map(opp => `
        <tr>
          <td><strong>${opp.company}</strong></td>
          <td>${opp.title}</td>
          <td><span class="badge badge-info">${opp.stage}</span></td>
          <td><span class="badge ${opp.handoffStatus === 'accepted' ? 'badge-success' : 'badge-warning'}">${opp.handoffStatus}</span></td>
          <td>${opp.value ? `$${opp.value.toLocaleString()}` : '&mdash;'}</td>
          <td>${opp.nextStep || '&mdash;'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  ` : ''}

  <div class="footer">
    <div>Confidential &mdash; Prepared for ${snapshot.meta.clientName}</div>
    <div>Generated on ${new Date().toLocaleDateString()} by SalesFlow Platform</div>
  </div>
</body>
</html>`;
}
