# App secrets. The three app secrets below are generated by Terraform; the whole runtime
# env is assembled into ONE JSON secret in Secrets Manager. deploy.sh renders it to
# .env.production on the box. Optional keys (AI/search provider keys, tracking, kill switch)
# can be added later by editing the secret in the console — deploy.sh picks them up as-is.

# V2_AUTH_SECRET — session signing key (app expects base64url, 32 bytes).
resource "random_id" "auth_secret" {
  byte_length = 32
}

# V2_OUTREACH_CREDENTIAL_KEY — AES-256-GCM master key (app expects base64, 32 bytes).
resource "random_id" "outreach_key" {
  byte_length = 32
}

# V2_WORKER_SECRET — gates /v2/outreach/drain + /v2/runtime/health.
resource "random_id" "worker_secret" {
  byte_length = 24
}

locals {
  database_url = "postgresql://${var.db_username}:${random_password.db.result}@${aws_db_instance.main.address}:5432/${var.db_name}?schema=public"
  redis_url    = "redis://${aws_elasticache_cluster.redis.cache_nodes[0].address}:6379"

  app_env = {
    NODE_ENV = "production"

    DATABASE_URL  = local.database_url
    V2_DB_POOL_MAX = "24"

    NEXT_PUBLIC_APP_URL = local.app_url
    APP_BASE_URL        = local.app_url
    APP_URL             = local.app_url

    V2_AUTH_SECRET       = random_id.auth_secret.b64_url
    V2_AUTH_COOKIE_NAME  = "v2_session"
    V2_AUTH_SESSION_DAYS = "14"

    V2_BULL_ENABLED = "true"
    REDIS_URL       = local.redis_url
    V2_BULL_PREFIX  = "telestar:v2"

    V2_WORKER_SECRET      = random_id.worker_secret.hex
    V2_WORKER_APP_URL     = "http://web:3000"
    V2_WORKER_INTERVAL_MS = "15000"

    V2_OUTREACH_CREDENTIAL_KEY = random_id.outreach_key.b64_std
    V2_IMAP_POLL_INTERVAL_MS   = "60000"

    AI_ENABLED                   = "false"
    COMPANY_INTEL_SEARCH_ENABLED = "false"
  }
}

resource "aws_secretsmanager_secret" "app_env" {
  name        = "${var.project}/${var.env}/env"
  description = "TeleStar V2 runtime env bundle (rendered to .env.production on the host)."
  tags        = { Name = "${local.name}-env" }
}

resource "aws_secretsmanager_secret_version" "app_env" {
  secret_id     = aws_secretsmanager_secret.app_env.id
  secret_string = jsonencode(local.app_env)
}
