import type { IcpVersionRules } from "../types";

export const TELSTAR_SAAS_OUTBOUND_ICP_RULES_FIXTURE = {
  schemaVersion: "v1",
  ruleSetId: "telestar-saas-outbound-v1",
  displayName: "Telestar SaaS Outbound ICP v1",
  missingWebsitePolicy: "review_required",
  geography: {
    targetCountries: [
      "United States",
      "Singapore",
      "Australia",
      "United Kingdom",
      "Canada",
      "Israel",
      "Norway",
      "Switzerland",
      "Denmark",
      "Sweden",
    ],
    excludedCountries: ["India", "Pakistan", "Bangladesh", "Philippines"],
    unknownCountryPolicy: "review_required",
    targetCountryScoreBoost: 3,
    excludedCountrySeverity: "strong_penalty",
  },
  companySize: {
    minEmployees: 3,
    unknownSizePolicy: "review_required",
    minEmployeesSeverity: "strong_penalty",
  },
  hardGates: [
    {
      id: "personal_email_domain",
      label: "Personal email domain",
      field: "emailDomainType",
      operator: "equals",
      value: "personal",
      severity: "strong_penalty",
      missingDataPolicy: "low_confidence_continue",
      maxScoreIfTriggered: 35,
      reasonCode: "personal_email_signal",
    },
    {
      id: "excluded_country",
      label: "Excluded country",
      field: "companyCountry",
      operator: "in",
      value: ["India", "Pakistan", "Bangladesh", "Philippines"],
      severity: "strong_penalty",
      missingDataPolicy: "review_required",
      maxScoreIfTriggered: 35,
      reasonCode: "excluded_country_signal",
    },
    {
      id: "minimum_employee_count",
      label: "Minimum employee count",
      field: "employeeCount",
      operator: "lt",
      value: 3,
      severity: "strong_penalty",
      missingDataPolicy: "review_required",
      maxScoreIfTriggered: 35,
      reasonCode: "minimum_employee_count_signal",
    },
  ],
  positiveSignals: [
    {
      id: "pricing_or_product_page",
      label: "Pricing or product evidence",
      direction: "positive",
      weight: 12,
      reliabilityPrior: 0.85,
      evidenceSources: ["website_subpage", "website_metadata"],
      keywords: ["pricing", "product", "platform", "demo"],
      websitePaths: ["/pricing", "/product", "/platform", "/demo"],
      reasonCode: "product_evidence",
    },
    {
      id: "api_or_developer_docs",
      label: "API or developer documentation",
      direction: "positive",
      weight: 10,
      reliabilityPrior: 0.85,
      evidenceSources: ["website_subpage", "website_metadata"],
      keywords: ["api", "developer", "documentation", "docs"],
      websitePaths: ["/api", "/docs", "/developers"],
      reasonCode: "technical_product_evidence",
    },
    {
      id: "b2b_saas_language",
      label: "B2B SaaS language",
      direction: "positive",
      weight: 8,
      reliabilityPrior: 0.7,
      evidenceSources: ["csv_field", "website_homepage", "website_subpage"],
      keywords: ["saas", "software", "platform", "workflow", "automation"],
      reasonCode: "b2b_saas_signal",
    },
  ],
  negativeSignals: [
    {
      id: "service_only_language",
      label: "Service-only language",
      direction: "negative",
      weight: 15,
      reliabilityPrior: 0.75,
      evidenceSources: ["website_homepage", "website_subpage"],
      keywords: ["agency", "consulting", "outsourcing"],
      reasonCode: "service_only_signal",
    },
    {
      id: "consumer_only_language",
      label: "Consumer-only language",
      direction: "negative",
      weight: 10,
      reliabilityPrior: 0.65,
      evidenceSources: ["csv_field", "website_homepage", "website_subpage"],
      keywords: ["b2c", "consumer app", "marketplace", "retail only"],
      reasonCode: "consumer_only_signal",
    },
  ],
  companyTypeRules: [
    {
      id: "product_saas",
      type: "product_saas",
      positiveKeywords: ["saas", "software", "subscription", "platform"],
      negativeKeywords: ["agency", "outsourcing"],
      defaultScoreImpact: 12,
      defaultConfidenceImpact: 0.12,
    },
    {
      id: "product_platform",
      type: "product_platform",
      positiveKeywords: ["platform", "api", "developer", "infrastructure"],
      negativeKeywords: ["consulting", "services only"],
      defaultScoreImpact: 10,
      defaultConfidenceImpact: 0.1,
    },
    {
      id: "service_plus_product",
      type: "service_plus_product",
      positiveKeywords: ["platform", "product", "software"],
      negativeKeywords: ["services", "implementation", "consulting"],
      defaultScoreImpact: 4,
      defaultConfidenceImpact: -0.05,
      reviewRequired: true,
    },
    {
      id: "service_only",
      type: "service_only",
      positiveKeywords: ["services", "agency", "consulting", "outsourcing"],
      defaultScoreImpact: -15,
      defaultConfidenceImpact: 0.05,
      reviewRequired: true,
    },
  ],
  confidencePolicy: {
    minimumEvidenceCountForHighConfidence: 2,
    highConfidenceThreshold: 0.7,
    lowConfidenceThreshold: 0.45,
    missingCriticalFieldPenalty: 0.15,
    conflictingEvidencePenalty: 0.2,
  },
  scorePolicy: {
    minScore: 0,
    maxScore: 100,
    qualifiedThreshold: 75,
    unqualifiedThreshold: 35,
    preserveV1BranchScoresUntilParity: true,
  },
} satisfies IcpVersionRules;
